resources:
  - name: ecr_webhook
    type: IncomingWebhook
    configuration:
      webhookName: webhook_ecr_list

pipelines:
  - name: PullRecentECRImages_Boto3AndDocker
    configuration:
      environmentVariables:
        readOnly:
          ARTIFACTORY_USER: danielw@jfrog.com
          REMOTE_REPO: danielw-ecr-list-images-docker-remote
    steps:
    - name: RunPythonScript
      type: Bash
      configuration:
        integrations:
          - name: artifactory
        inputResources:
          - name: ecr_webhook
          - name: ecr_list_gitrepo
            trigger: false
      execution:
          onExecute:
            - python3 --version
            - pip3 --version
            - ls -lR
            - cp ./dependencyState/resources/ecr_list_gitrepo/ecr-image-list/requirements.txt .
            - pip3 install -r requirements.txt
            - cp ./dependencyState/resources/ecr_list_gitrepo/ecr-image-list/using-boto3-and-docker.py .
            - python3 using-boto3-and-docker.py
